from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 880)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("style.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(150, 0, 20, 880))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(170, 0, 900, 880))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.label_1 = QtWidgets.QLabel(self.page_0)
        self.label_1.setGeometry(QtCore.QRect(20, 20, 400, 400))
        self.label_1.setText("")
        #self.label_1.setPixmap(QtGui.QPixmap("../image/iconJpeg.png"))
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label_2 = QtWidgets.QLabel(self.page_0)
        self.label_2.setGeometry(QtCore.QRect(440, 20, 400, 400))
        self.label_2.setText("")
        #self.label_2.setPixmap(QtGui.QPixmap("../image/iconPng.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_0)
        self.label_3 = QtWidgets.QLabel(self.page_0)
        self.label_3.setGeometry(QtCore.QRect(20, 420, 400, 400))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../image/iconPng.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_0)
        self.label_4.setGeometry(QtCore.QRect(440, 420, 400, 400))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../image/iconPng.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.page_0)
        self.formLayoutWidget.setGeometry(QtCore.QRect(440, 440, 400, 400))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_1 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_1.setContentsMargins(0, 0, 0, 0)
        self.formLayout_1.setObjectName("formLayout_1")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_1.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_1.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_1.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.page_1)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(470, 430, 271, 131))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)

        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 141, 351))
        self.toolBox.setMinimumSize(QtCore.QSize(0, 351))
        self.toolBox.setStyleSheet("font: 5.65pt \"Arial\";")
        self.toolBox.setLineWidth(8)
        self.toolBox.setObjectName("toolBox")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.toolBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 131, 140))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.layout_T1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.layout_T1.setContentsMargins(0, 0, 0, 0)
        self.layout_T1.setObjectName("layout_T1")
        self.pushButton_01 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_01.sizePolicy().hasHeightForWidth())
        self.pushButton_01.setSizePolicy(sizePolicy)
        self.pushButton_01.setMinimumSize(QtCore.QSize(60, 25))
        self.pushButton_01.setMaximumSize(QtCore.QSize(250, 60))
        self.pushButton_01.setObjectName("pushButton_01")
        self.layout_T1.addWidget(self.pushButton_01)
        self.pushButton_02 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_02.sizePolicy().hasHeightForWidth())
        self.pushButton_02.setSizePolicy(sizePolicy)
        self.pushButton_02.setMinimumSize(QtCore.QSize(60, 25))
        self.pushButton_02.setMaximumSize(QtCore.QSize(160, 60))
        self.pushButton_02.setObjectName("pushButton_02")
        self.layout_T1.addWidget(self.pushButton_02)
        self.pushButton_03 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_03.sizePolicy().hasHeightForWidth())
        self.pushButton_03.setSizePolicy(sizePolicy)
        self.pushButton_03.setMinimumSize(QtCore.QSize(60, 25))
        self.pushButton_03.setMaximumSize(QtCore.QSize(160, 60))
        self.pushButton_03.setObjectName("pushButton_03")
        self.layout_T1.addWidget(self.pushButton_03)
        self.pushButton_04 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_04.sizePolicy().hasHeightForWidth())
        self.pushButton_04.setSizePolicy(sizePolicy)
        self.pushButton_04.setMinimumSize(QtCore.QSize(60, 25))
        self.pushButton_04.setMaximumSize(QtCore.QSize(160, 60))
        self.pushButton_04.setObjectName("pushButton_04")
        self.layout_T1.addWidget(self.pushButton_04)


        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 380, 141, 291))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.leftFrame_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.leftFrame_2.setContentsMargins(0, 0, 0, 0)
        self.leftFrame_2.setObjectName("leftFrame_2")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.leftFrame_2.addWidget(self.lineEdit)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_3)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.leftFrame_2.addWidget(self.plainTextEdit)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 23))
        self.menubar.setObjectName("menubar")
        self.menuQuit = QtWidgets.QMenu(self.menubar)
        self.menuQuit.setObjectName("menuQuit")
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.setCentralWidget(self.centralwidget)


        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../image/iconQuit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon4)
        self.actionQuit.setObjectName("actionQuit")
        self.menuQuit.addAction(self.actionQuit)
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.pushButton_01.clicked.connect(MainWindow.click_pushButton_01)
        self.pushButton_02.clicked.connect(MainWindow.click_pushButton_02)
        self.pushButton_03.clicked.connect(MainWindow.click_pushButton_03)
        self.pushButton_04.clicked.connect(MainWindow.click_pushButton_04)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Product Stylization Designer v0.1"))
        self.pushButton_01.setText(_translate("MainWindow", "Open Content Image"))
        self.pushButton_02.setText(_translate("MainWindow", "Open Style Image"))
        self.pushButton_03.setText(_translate("MainWindow", "Content Image Segmentation"))
        self.pushButton_04.setText(_translate("MainWindow", "Stylize"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
